#include "shaderlib/cshader.h"
class tdc_flesh_interior_blended_pass_ps30_Static_Index
{
public:
	tdc_flesh_interior_blended_pass_ps30_Static_Index( )
	{
	}
	int GetIndex()
	{
		// Asserts to make sure that we aren't using any skipped combinations.
		// Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
		return 0;
	}
};
#define shaderStaticTest_tdc_flesh_interior_blended_pass_ps30 0
class tdc_flesh_interior_blended_pass_ps30_Dynamic_Index
{
public:
	tdc_flesh_interior_blended_pass_ps30_Dynamic_Index()
	{
	}
	int GetIndex()
	{
		// Asserts to make sure that we aren't using any skipped combinations.
		// Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
		return 0;
	}
};
#define shaderDynamicTest_tdc_flesh_interior_blended_pass_ps30 0
