//=============================================================================//
//
// Purpose: 
//
//=============================================================================//
#ifndef TDC_ANNOUNCER_H
#define TDC_ANNOUNCER_H

#ifdef _WIN32
#pragma once
#endif

#include "igamesystem.h"

enum
{
	TDC_ANNOUNCER_STALEMATE = 0,
	TDC_ANNOUNCER_SUDDENDEATH,
	TDC_ANNOUNCER_VICTORY,
	TDC_ANNOUNCER_DEFEAT,
	TDC_ANNOUNCER_OVERTIME,
	TDC_ANNOUNCER_ROUNDBEGINS_60SEC,
	TDC_ANNOUNCER_ROUNDBEGINS_30SEC,
	TDC_ANNOUNCER_ROUNDBEGINS_10SEC,
	TDC_ANNOUNCER_ROUNDBEGINS_5SEC,
	TDC_ANNOUNCER_ROUNDBEGINS_4SEC,
	TDC_ANNOUNCER_ROUNDBEGINS_3SEC,
	TDC_ANNOUNCER_ROUNDBEGINS_2SEC,
	TDC_ANNOUNCER_ROUNDBEGINS_1SEC,
	TDC_ANNOUNCER_ROUNDENDS_5MIN,
	TDC_ANNOUNCER_ROUNDENDS_60SEC,
	TDC_ANNOUNCER_ROUNDENDS_30SEC,
	TDC_ANNOUNCER_ROUNDENDS_10SEC,
	TDC_ANNOUNCER_ROUNDENDS_5SEC,
	TDC_ANNOUNCER_ROUNDENDS_4SEC,
	TDC_ANNOUNCER_ROUNDENDS_3SEC,
	TDC_ANNOUNCER_ROUNDENDS_2SEC,
	TDC_ANNOUNCER_ROUNDENDS_1SEC,
	TDC_ANNOUNCER_TIMEADDED,
	TDC_ANNOUNCER_TIMEADDED_TEAM,
	TDC_ANNOUNCER_TIMEADDED_ENEMY,
	TDC_ANNOUNCER_CTF_ENEMYSTOLEN,
	TDC_ANNOUNCER_CTF_ENEMYDROPPED,
	TDC_ANNOUNCER_CTF_ENEMYCAPTURED,
	TDC_ANNOUNCER_CTF_ENEMYRETURNED,
	TDC_ANNOUNCER_CTF_TEAMSTOLEN,
	TDC_ANNOUNCER_CTF_TEAMDROPPED,
	TDC_ANNOUNCER_CTF_TEAMCAPTURED,
	TDC_ANNOUNCER_CTF_TEAMRETURNED,
	TDC_ANNOUNCER_AD_ENEMYSTOLEN,
	TDC_ANNOUNCER_AD_ENEMYDROPPED,
	TDC_ANNOUNCER_AD_ENEMYCAPTURED,
	TDC_ANNOUNCER_AD_ENEMYRETURNED,
	TDC_ANNOUNCER_AD_TEAMSTOLEN,
	TDC_ANNOUNCER_AD_TEAMDROPPED,
	TDC_ANNOUNCER_AD_TEAMCAPTURED,
	TDC_ANNOUNCER_AD_TEAMRETURNED,
	TDC_ANNOUNCER_INVADE_ENEMYSTOLEN,
	TDC_ANNOUNCER_INVADE_ENEMYDROPPED,
	TDC_ANNOUNCER_INVADE_ENEMYCAPTURED,
	TDC_ANNOUNCER_INVADE_TEAMSTOLEN,
	TDC_ANNOUNCER_INVADE_TEAMDROPPED,
	TDC_ANNOUNCER_INVADE_TEAMCAPTURED,
	TDC_ANNOUNCER_INVADE_RETURNED,
	TDC_ANNOUNCER_SD_ENEMYSTOLEN,
	TDC_ANNOUNCER_SD_ENEMYDROPPED,
	TDC_ANNOUNCER_SD_ENEMYCAPTURED,
	TDC_ANNOUNCER_SD_TEAMSTOLEN,
	TDC_ANNOUNCER_SD_TEAMDROPPED,
	TDC_ANNOUNCER_SD_TEAMCAPTURED,
	TDC_ANNOUNCER_SD_RETURNED,
	TDC_ANNOUNCER_SD_ROUNDSTART,
	TDC_ANNOUNCER_CONTROLPOINT_CONTESTED,
	TDC_ANNOUNCER_CONTROLPOINT_CONTESTED_NEUTRAL,
	TDC_ANNOUNCER_CART_WARNING_ATTACKER,
	TDC_ANNOUNCER_CART_WARNING_DEFENDER,
	TDC_ANNOUNCER_CART_FINALWARNING_ATTACKER,
	TDC_ANNOUNCER_CART_FINALWARNING_DEFENDER,
	TDC_ANNOUNCER_ARENA_ROUNDSTART,
	TDC_ANNOUNCER_ARENA_FIRSTBLOOD,
	TDC_ANNOUNCER_ARENA_FIRSTBLOOD_FAST,
	TDC_ANNOUNCER_ARENA_FIRSTBLOOD_FINALLY,
	TDC_ANNOUNCER_ARENA_CAPENABLED,
	TDC_ANNOUNCER_ARENA_FLAWLESSVICTORY,
	TDC_ANNOUNCER_ARENA_FLAWLESSVICTORY_TEAM,
	TDC_ANNOUNCER_ARENA_FLAWLESSVICTORY_ENEMY,
	TDC_ANNOUNCER_ARENA_TEAMSCRAMBLE,
	TDC_ANNOUNCER_ARENA_LASTSTANDING,
	TDC_ANNOUNCER_SECURITYALERT,
	TDC_ANNOUNCER_MVM_BOMBRESET,
	TDC_ANNOUNCER_DM_CRIT_INCOMING,
	TDC_ANNOUNCER_DM_SHIELD_INCOMING,
	TDC_ANNOUNCER_DM_HASTE_INCOMING,
	TDC_ANNOUNCER_DM_BERSERK_INCOMING,
	TDC_ANNOUNCER_DM_CLOAK_INCOMING,
	TDC_ANNOUNCER_DM_MEGAHEALTH_INCOMING,
	TDC_ANNOUNCER_DM_DISPLACER_INCOMING,
	TDC_ANNOUNCER_DM_CRIT_SPAWN,
	TDC_ANNOUNCER_DM_SHIELD_SPAWN,
	TDC_ANNOUNCER_DM_HASTE_SPAWN,
	TDC_ANNOUNCER_DM_BERSERK_SPAWN,
	TDC_ANNOUNCER_DM_CLOAK_SPAWN,
	TDC_ANNOUNCER_DM_MEGAHEALTH_SPAWN,
	TDC_ANNOUNCER_DM_DISPLACER_SPAWN,
	TDC_ANNOUNCER_DM_CRIT_TEAMPICKUP,
	TDC_ANNOUNCER_DM_SHIELD_TEAMPICKUP,
	TDC_ANNOUNCER_DM_HASTE_TEAMPICKUP,
	TDC_ANNOUNCER_DM_BERSERK_TEAMPICKUP,
	TDC_ANNOUNCER_DM_CLOAK_TEAMPICKUP,
	TDC_ANNOUNCER_DM_MEGAHEALTH_TEAMPICKUP,
	TDC_ANNOUNCER_DM_DISPLACER_TEAMPICKUP,
	TDC_ANNOUNCER_DM_CRIT_ENEMYPICKUP,
	TDC_ANNOUNCER_DM_SHIELD_ENEMYPICKUP,
	TDC_ANNOUNCER_DM_HASTE_ENEMYPICKUP,
	TDC_ANNOUNCER_DM_BERSERK_ENEMYPICKUP,
	TDC_ANNOUNCER_DM_CLOAK_ENEMYPICKUP,
	TDC_ANNOUNCER_DM_MEGAHEALTH_ENEMYPICKUP,
	TDC_ANNOUNCER_DM_DISPLACER_ENEMYPICKUP,
	TDC_ANNOUNCER_DM_LEADTAKEN,
	TDC_ANNOUNCER_DM_LEADLOST,
	TDC_ANNOUNCER_DM_LEADTIED,
	TDC_ANNOUNCER_INFECTION_HUMANSWIN,
	TDC_ANNOUNCER_INFECTION_ZOMBIESWIN,
	TDC_ANNOUNCER_PD_CAPTUREZONE_ACTIVE,
	TDC_ANNOUNCER_PD_CAPTUREZONE_INACTIVE,
	TDC_ANNOUNCER_PD_TEAM_INZONE,
	TDC_ANNOUNCER_PD_ENEMY_INZONE,

	TDC_ANNOUNCER_MESSAGE_COUNT
};

class CTDCAnnouncer : public CAutoGameSystem
{
public:
	CTDCAnnouncer( const char *pszName );

	virtual bool Init( void );
	virtual void LevelInitPreEntity( void );

	const char *GetSoundForMessage( int iMessage );
	
#ifdef GAME_DLL
	void Speak( IRecipientFilter &filter, int iMessage );
	void Speak( int iMessage );
	void Speak( CBasePlayer *pPlayer, int iMessage );
	void Speak( int iTeam, int iMessage );
#else
	void Speak( int iMessage );
#endif

	enum
	{
		TDC_ANNOUNCERTYPE_VOX = 0,
		TDC_ANNOUNCERTYPE_COUNT,
	};

	static const char *m_aAnnouncerSounds[TDC_ANNOUNCERTYPE_COUNT][TDC_ANNOUNCER_MESSAGE_COUNT];
};

extern CTDCAnnouncer g_TFAnnouncer;

#endif // TDC_ANNOUNCER_H
